### PR TITLE
ENH: conda testing dockerfile

### PR DESCRIPTION
**Pull request by klauer**
Add `Dockerfile` and helper scripts for running our CI configuration on a similar-to-Travis container locally: this time for conda instead of pypi. I've renamed this repo accordingly.

* Both of these could have used layering better, but this was the expedient (code word for lazy) approach. 
* Initial test: `======================================== 207 passed, 1 xpassed, 53 warnings in 127.56s (0:02:07) ========================================`

### CODE REVIEW

**Review by ZLLentz — APPROVED** [review]
Looks like this worked to reproduce the issue as in https://github.com/pcdshub/typhos/issues/526#issuecomment-1306090240 (?)

**Comment by tangkong** [comment]
The conda docker seemed to stall for me on "reloading output folder..." then fails after a good deal of waiting.  Is this another mac M1 issue?  Who knows...
```
#18 114.9 + conda mambabuild -q conda-recipe --output-folder bld-dir --no-anaconda-upload
#18 119.9 No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
#18 119.9 WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
#18 120.2 Updating build index: /home/travis/pcdshub/pcdsdevices/bld-dir
#18 120.2
#18 120.2 Copying /home/travis/pcdshub/pcdsdevices to /home/travis/micromamba/conda-bld/pcdsdevices_1667861921323/work/
#18 120.2 Adding in variants from internal_defaults
#18 120.2 INFO:conda_build.variants:Adding in variants from internal_defaults
#18 126.0 Attempting to finalize metadata for pcdsdevices
#18 126.0 INFO:conda_build.metadata:Attempting to finalize metadata for pcdsdevices
#18 130.5 conda-forge/linux-64                                        Using cache
#18 130.5 conda-forge/noarch                                          Using cache
#18 132.8 Reloading output folder: /home/travis/pcdshub/pcdsdevices/bld-dir
#18 555.4 Reloading output folder: /home/travis/pcdshub/pcdsdevices/bld-dir
#18 559.4 BUILD START: ['pcdsdevices-0+untagged.1.g0266b42-py_1.tar.bz2']
#18 559.4 Reloading output folder: /home/travis/pcdshub/pcdsdevices/bld-dir
#18 562.6 Reloading output folder: /home/travis/pcdshub/pcdsdevices/bld-dir
#18 568.2 ./build.sh: line 37:   690 Killed                  conda mambabuild -q "$CONDA_RECIPE_FOLDER" --output-folder bld-dir --no-anaconda-upload
#18 ERROR: executor failed running [/bin/sh -c ./build.sh]: exit code: 137
------
 > [10/13] RUN ./build.sh:
------
executor failed running [/bin/sh -c ./build.sh]: exit code: 137
make: *** [build-image] Error 1
```

the pip version works for me, but the conda container stalls for both typhos (as written in this PR) and pcdsdevices :\

**Comment by klauer** [comment]
Seems like it may be related to this, @tangkong? https://github.com/mamba-org/boa/issues/213
Oddly I don't see that result - which should not be the case for docker...

**Comment by klauer** [comment]
@ZLLentz, yes, for me at least, I was able to reproduce it pretty easily

**Pull request merged**
